# Navigation Bar Links
#   The weight parameter defines the order that the links will appear in.

[[main]]
    name = "Install"
    url = "/install/"
    weight = 1
[[main]]
    name = "Packages"
    url = "/packages/"
    weight = 2
[[main]]
    name = "Gallery"
    url = "/gallery/"
    weight = 3
[[main]]
    name = "Learn"
    url = "/learn/"
    weight = 4
[[main]]
    name = "Articles"
    url = "/news/"
    weight = 5
[[main]]
    name = "Publications"
    url = "/publications/"
    weight = 6
[[main]]
    name = "Help"
    url = "/help/"
    weight = 7
[[main]]
    name = "Contribute"
    url = "/contribute/"
    weight = 8
[[main]]
    name = "Team"
    url = "/author/"
    weight = 9
    