git:
  depth: false
env:
  global:
  - HUGO_VERSION="0.54.0"
  matrix:
  - YOUR_ENCRYPTED_VARIABLE
  - secure: IS79e126c6tkaOtwnAoYBBMclIz4vjesTgoiQkGOiFUbx0R1RzWMA0orjaYkR0rZX9NQ54xclCS1MMJ0qU4rFWo2/It7WZDZHOtUdG1xr2TTIytJB+pEzUxy+VZAO6qTaI8YVju0Jgah76pYv8i8S4IOOMj0XYiDWS3ENcnD4abJpdNKGE2MOWWR2g/bfU7dWsDbOUAj6sPQldj2t6joaxKKYDnuu6QQP99APEJnHWdyeVHJ0MVh9K5lj7CS8TKOs38GpdcgVreYJ2Hrm1YTSRKEM9kbe4FENFmXJKX6N1Fy/ZC3nnNwr4DDmhPi6ZJ2Bw+VN0w7DOPhgpL2+TV/56SwUl9OO8XCn+ML9BuvBzhmE5p9wNV0M+TpA6qilmqGQSnRYQaRLuqIpEdrQ/n9kpX8eRuS3IZsPwrFnzzv8wyuD2cB0JzPxUIz2ig1SAkQmkdIAGSbyX24BzFtGRvBGq4wwU1ADmJE//mJMccAXaMMklRGzzrNo/lffjWxTC4GEEiYybj+EXXkHhi+DLuGmTPSpgnkChIn3y4lTDeLoLB7K6McuVllEVwlY3R9pohj4dk9ya7Yp6i5LowsJCEuyD+y4ojZHAI7iIPzO1YlcaijEF4TwpaEFXsqro1tlmLEgJSZV/mUYoLDFS7A///sz8NZvdywFGfSsoI2Wx1mW6k=
install:
- wget -q https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
- tar xf hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
- mv hugo ~/bin/
script:
- hugo --gc --minify
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep_history: false
  local_dir: public
  repo: natverse/natverse.github.io
  target_branch: master
  verbose: true
  on: 
  branch: master
