git:
  depth: false
env:
  global:
  - HUGO_VERSION="0.54.0"
  matrix:
  - YOUR_ENCRYPTED_VARIABLE
  - secure: KPfj7Z67wil8NVDiOSofbRF74NUImArJu3WtWKFXvoiVd959wAOGghSVH4b6ZQRsipJi5uWTSN8ypoQ/50LPp/1lYMTjCLxGK/Gl4yhrojibvlgc8uz+voI6JWOc2sYi7MdA6rL5gRdDBm76ImQAHDHDrxf+XTQaqEWO4AnlbwFqblofYo0Cr0dBI29t82kmf8o6M1Uuh2Vo0UyMUFswcx5y0ZxHFrAPT9uAuMT0jm0BNBuGebN7Dj3CHip36j8npo62xSlHviMdvHftWtj76wvbgwOCDDZei+sDefvrGYr/QGrPekL4/tMluBaItT3GtOKwWY89hVQPbzE4Yxynstl0z/XRfyzbKjFJcxhf9ZYgGttwIXXv0F6VOYg7VBePdrOh4ZCOC/7dAZeODxH344Z8IrvJH1G962PzoN8UnWnLF/bwcWoFMZ131+UkZwTvjPvX1eXzP80wwh/jHAZ5MCIwyrSdDiEnGtLUgUXxbPtIj96ZSMK9s8lfrJGmjvs1NTLLAd+i1M9AAKnu2uIKC+F4K7yjIXlbTeBlScj7bnzqrzMBewrsuEw0h9mDEokDKoJjebGjPx2FR8E8a6Cl+E4nRXOZNN7K/V35XQFmKKvaM9uVQs4w3BaW1X+4BefwDf/zBXJRSJBafpY8PCh9qXEGko/NehPEP+8P9uRyEI4=
  - secure: NL8VPyDvUHQSUC/82AvT/tGslY72geKyrgBPiqiXQ2kBGwcNPTJKK9tVOCAOoICu5qnkwhK/vnQZLv2LZ13RDy9i2q+XEmTKyxiQ8M8hBSRQjBnwXEyHa2QDEcPJWWsAromeI+QGODU+jEz3DdhVCF42epOG4SPQEWPo7hTQywbWnkbvlh1VRiUmh0FneaNOgRTsba3KEWnQHfy2OoYw/QAwwgI8rYYDJXjKIBGRmd1XKW6Q26dB108DWTHywitIUaxg+JzT0i5e5udIpRIiVd8+uM5PFRZn5/HNvz5B/UVuJc5/alKO/oXhpG3Mwx1YuQntnMjOvAkX4VOdvUCeo0XoV1+9HcmGeTw3lHujRe+OPJKNWFp6i+NFofVKgzp0Nc5DfuLp+MC59TTDqkP2B99jsFrD4ch+8gC/VjfxBl2dmzC7pXdrDHDXsFVQNn/tbUAnDnpSDbiYrTD43Mnth0mFMSodmOwNWiF99wu37yIEG6lJk2jY26e4fl5+o3348rLQ+Wp+DU0DnbvOsGFqXqRRTd9noGMy46E+aVaxck4yK5HByYd0p8v73Bdvo7XhRtOgQrRhvWYed9COAAGYlCNl6oo74VNJRzPUllDnpAEN7xj+BwZaIWaItZ6YefMIe1RTcxnmdrOXn/EH+dxdmQIGZkE8HsPsydSGKq06EbE=
  - secure: ewXXXkZwLrGmByzVGiUuLwPaCxa7/7pY7lMA6bQaYAvmtpNn2w2PkSs0QHq5wyh9PmC/P5uqnsYbIirZUB4sKFcg/ldLSJX3hufglq4vIGrPUWvbo2PwH4WN0zjWZ4Kb3rENUtrrErtQ4UEgDP0DpMPFn4K8SaGD6MaLBAVCicbm/NjDcVEzi5gNUv7knaeOV/S4cfW3MWpbqJOvMWdUh7V+TPc4Ap3yzAEZ2DnPcuoM5LiAejoxuQVEtagPZifpEPVcuSEHUjeWBNp56oN77Zf2Djg5w6AJ+IRC9NhTsjL/k5Mm6HY6W5XtWjec3C200jtTc4bPJGnQcHJ8BPuAeJ82GFHOLF02yI/pV28alPbLILUL5s9oH++mSc2wtrbe+pGhVWNrIxt6Sfa05QE7yC4pHjadhNOC7dmQPThrL725NkH0QlrQp1R2kooEmokRiAaUX0FG+DTJivltoKJyl9KI4PZWDGlHXbD4ne5jU+UrKfbHTG3tzNOXqNeZGTIaixAPtTWutwqlvaCYf2baZOIK7ZO3F6tyRb74937BPcYknuxVGBlGAigdZNW0TpAQ5LaAfScWcOnXO1Dh3Dar8BEzXMmNxqEGpHJXMErJ+fkmlC+rcf+HujbqjFWBQaX1JTLBshzBCBWPZlwqtWa1FxpoqqP9HHDBI2Ukyv7uYs8=
install:
- wget -q https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
- tar xf hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
- mv hugo ~/bin/
script:
- hugo --gc --minify
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep_history: false
  local_dir: public
  repo: natverse/natverse.github.io
  target_branch: master
  verbose: true
  on: 
  branch: master
